# Generated by scripts/release/package.sh in ItsReidar/brain-md from
# packaging/homebrew/brain-md.rb.template — edit the template there, not this file.
cask "brain-md" do
  version "1.0"
  sha256 "e6c4e280a045efc7a92bf304fe7a282759e723b6ef35ee6e41dd9e1b57e92647"

  url "https://github.com/ItsReidar/brain-md/releases/download/v#{version}/brain-md-#{version}.dmg"
  name "Brain.md"
  desc "Markdown notes editor with live preview and a built-in MCP server"
  homepage "https://github.com/ItsReidar/brain-md"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: :tahoe

  app "brain-md.app"

  # Never touches the notes vault (defaults to ~/Documents); only app-owned state.
  zap trash: [
    "~/Library/Caches/itsreidar.brain-md",
    "~/Library/HTTPStorages/itsreidar.brain-md",
    "~/Library/Preferences/itsreidar.brain-md.plist",
    "~/Library/Saved Application State/itsreidar.brain-md.savedState",
    "~/Library/WebKit/itsreidar.brain-md",
  ]

  caveats <<~EOS
    Brain.md is not notarized by Apple, so macOS blocks its first launch.
    Allow it in one of these ways (and again after each upgrade):

      - Open Brain.md once, then go to System Settings > Privacy & Security
        and click "Open Anyway" next to the message about Brain.md.

      - Or remove the download quarantine flag in Terminal (no sudo needed):
          xattr -dr com.apple.quarantine "#{appdir}/brain-md.app"
  EOS
end
